name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Mainnet Forking Tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          CULITO: "HOLAAAAAAAA"
        run: echo $CULITO
      - run: npm install
      - run: echo $PATH
      - run: echo $MAINNET_RPC_URL
      - run: npx hardhat test
